### ISSUE TITLE
7.x-3.0-beta2 doesn't work at all

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop-contrib/radix#27]
I just downloaded the 7.x-3.0-beta2 release, but it doesn't seem to be configured properly. For one, the info file within it says the version is Radix 7.x-3.0-alpha2+4-dev instead. Second, when I go to my themes page, it says "This version is not compatible with Backdrop CMS 1.x and should be replaced."

**Comment by shadcn** [comment]
@mikemccaffrey You need the 1.x branch. https://github.com/backdrop-contrib/radix/archive/1.x.zip

7.x-3.0 is an old Drupal branch.
