### ISSUE TITLE
Array to string conversion errors

### ISSUE THREAD

**Issue by PaulHoza** [backdrop-contrib/radix#3]
On a new install of BD 1.x (currently 1.1.3) and Radix 1.x, I'm seeing a few errors when loading up the Style Guide (using the Backdrop module -https://github.com/backdrop-contrib/styleguide ).  

```
Notice: Array to string conversion in include() (line 62 of /home/example/public_html/themes/radix-1.x/templates/comment/comment.tpl.php).
Notice: Array to string conversion in include() (line 62 of /home/example/public_html/themes/radix-1.x/templates/comment/comment.tpl.php).
Notice: Array to string conversion in include() (line 79 of /home/example/public_html/themes/radix-1.x/templates/comment/comment.tpl.php).
```

I've compared the code from these sections to other code in working themes and have come up with some fixes... but I honestly don't know what I'm doing enough to know _why_ these work(!)  I could use some help making sure this stuff is correct and not just some sort of an accidentally working hack.

(I'll just post a PR with the examples of what I have working, instead of figuring out a decent way to put it in here.)

**Comment by jenlampton** [comment]
sine both https://github.com/PaulHoza/radix/pull/1 and  https://github.com/backdrop-contrib/radix/pull/4 are merged, closing this issue.
